#!/usr/bin/env python3
"""Convert the MVHS clubs CSV export into INSERT statements for the clubs table."""

from __future__ import annotations

import csv
import pathlib
import re
import sys
from typing import List, Sequence


ROOT = pathlib.Path(__file__).resolve().parents[1]
CSV_FILENAME = "Official MVHS Clubs List 2025-2026 - Official list.csv"
OUTPUT_FILENAME = "mvhs_clubs_seed.sql"
EMAIL_PATTERN = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")


def clean(value: str | None) -> str | None:
    """Collapse internal whitespace and strip leading/trailing spaces."""

    if value is None:
        return None
    value = value.strip()
    if not value:
        return None
    return re.sub(r"\s+", " ", value)


def extract_emails(raw: str | None) -> str | None:
    """Return a normalized, comma-separated list of email addresses."""

    raw = clean(raw)
    if not raw:
        return None
    matches = [match.lower() for match in EMAIL_PATTERN.findall(raw)]
    if matches:
        # Deduplicate while preserving order.
        seen: set[str] = set()
        ordered: List[str] = []
        for email in matches:
            if email in seen:
                continue
            seen.add(email)
            ordered.append(email)
        return ", ".join(ordered)
    return raw


def build_meeting_schedule(row: dict[str, str | None]) -> str | None:
    parts: List[str] = []
    for heading in ("Meeting Day", "Meeting Frequency", "Meeting Time"):
        value = clean(row.get(heading)) if row.get(heading) is not None else None
        if value:
            parts.append(value)
    return " · ".join(parts) if parts else None


def build_record(idx: int, row: dict[str, str | None]) -> dict[str, object]:
    name = clean(row.get("Club Name"))
    if not name:
        raise ValueError(f"Row {idx} is missing a club name")

    description = clean(row.get("Mission Statement"))
    advisor = clean(row.get("Club Advisor"))
    advisor_email = extract_emails(row.get("Club Advisor Email"))
    president_email = extract_emails(row.get("Club President Email"))
    contact_email = president_email or advisor_email
    location = clean(row.get("Meeting Room Number"))
    meeting_schedule = build_meeting_schedule(row)

    return {
        "id": idx,
        "name": name,
        "alias_name": None,
        "description": description,
        "category": None,
        "meeting_schedule": meeting_schedule,
        "location": location,
        "contact_email": contact_email,
        "advisor": advisor,
        "image_url": None,
        "member_count": 0,
        "achievements": "JSON_ARRAY()",
        "school_id": 1,
    }


def sql_literal(value: object, raw_columns: set[str], column: str) -> str:
    if column in raw_columns:
        return value if isinstance(value, str) else str(value)
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value).replace("'", "''")
    return f"'{text}'"


def records_to_sql(records: Sequence[dict[str, object]]) -> str:
    if not records:
        raise RuntimeError("No club records were parsed from the CSV.")

    columns = [
        "id",
        "name",
        "alias_name",
        "description",
        "category",
        "meeting_schedule",
        "location",
        "contact_email",
        "advisor",
        "image_url",
        "member_count",
        "achievements",
        "school_id",
    ]
    raw_columns = {"achievements"}

    values_sql = []
    for record in records:
        row_parts = [sql_literal(record.get(column), raw_columns, column) for column in columns]
        values_sql.append("  (" + ", ".join(row_parts) + ")")

    lines = [
        "-- Auto-generated by scripts/generate_clubs_sql.py",
        f"-- Source CSV: {CSV_FILENAME}",
        "INSERT INTO clubs (" + ", ".join(columns) + ") VALUES",
        ",\n".join(values_sql) + ";",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    csv_path = ROOT / CSV_FILENAME
    output_path = ROOT / OUTPUT_FILENAME

    if not csv_path.exists():
        print(f"CSV file not found: {csv_path}", file=sys.stderr)
        return 1

    records: List[dict[str, object]] = []
    with csv_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        idx = 0
        for row in reader:
            # Some mission statements span multiple lines; DictReader handles them already.
            if not any(row.values()):
                continue
            idx += 1
            try:
                records.append(build_record(idx, row))
            except ValueError as exc:
                print(f"Skipping row {idx}: {exc}", file=sys.stderr)

    sql = records_to_sql(records)
    output_path.write_text(sql, encoding="utf-8")
    print(f"Wrote {len(records)} club rows to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
